# Generated by Django 5.2.1 on 2025-05-15 15:16

import unifi_auth_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifi_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unifiuser',
            options={'ordering': ['nome'], 'verbose_name': 'Usuário UniFi', 'verbose_name_plural': 'Usuários UniFi'},
        ),
        migrations.AlterField(
            model_name='unifiuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='unifiuser',
            name='mac_address',
            field=models.CharField(help_text='Formato: XX:XX:XX:XX:XX:XX ou XX-XX-XX-XX-XX-XX', max_length=17, unique=True, validators=[unifi_auth_app.models.validate_mac_address], verbose_name='MAC Address'),
        ),
        migrations.AlterField(
            model_name='unifiuser',
            name='matricula',
            field=models.CharField(max_length=20, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='unifiuser',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
