# Generated by Django 5.2.1 on 2025-05-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifi_auth_app', '0002_alter_unifiuser_options_alter_unifiuser_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiuser',
            name='lotacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lotação'),
        ),
    ]
