# Generated by Django 5.2.1 on 2025-05-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifi_auth_app', '0003_unifiuser_lotacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unifiuser',
            name='lotacao',
        ),
        migrations.AddField(
            model_name='unifiuser',
            name='departamento',
            field=models.CharField(choices=[('CER', 'Cerimonial'), ('ASC', 'Assessoria de Comunicação'), ('PRO', 'Procuradoria'), ('CNT', 'Controladoria Interna'), ('DIF', 'Diretoria Financeira'), ('DIL', 'Diretoria Legislativa'), ('DIA', 'Diretoria Administrativa'), ('OUV', 'Ouvidoria'), ('ILCM', 'Instituto Legislativo'), ('ARQ', 'Arquivo e Registro'), ('CONT', 'Contabilidade'), ('PAT', 'Patrimônio'), ('AUT', 'Automação'), ('MBL', 'Memorial e Biblioteca Legislativa'), ('RTV', 'Rádio e TV'), ('PLN', 'Planejamento de Contratações'), ('SIC', 'Serviço de Informação ao Cidadão'), ('LIC', 'Licitações e Contratos'), ('POL', 'Polícia Legislativa'), ('RH', 'Recursos Humanos'), ('MTS', 'Materiais e Serviços'), ('COM', 'Compras'), ('DTI', 'Departamento de Tecnologia da Informação')], default='DTI', max_length=4, verbose_name='Departamento'),
        ),
    ]
