# Generated by Django 5.2.1 on 2025-05-15 16:55

import django.db.models.deletion
import unifi_auth_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifi_auth_app', '0004_remove_unifiuser_lotacao_unifiuser_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unifiuser',
            name='mac_address',
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(help_text='Formato: XX:XX:XX:XX:XX:XX ou XX-XX-XX-XX-XX-XX', max_length=17, unique=True, validators=[unifi_auth_app.models.validate_mac_address], verbose_name='MAC Address')),
                ('nome_dispositivo', models.CharField(max_length=100, verbose_name='Nome do Dispositivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='unifi_auth_app.unifiuser')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'ordering': ['usuario__nome', 'nome_dispositivo'],
            },
        ),
    ]
