# Generated by Django 5.2.1 on 2025-05-15 16:59

import unifi_auth_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifi_auth_app', '0005_remove_unifiuser_mac_address_dispositivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='mac_address',
            field=models.CharField(help_text='Formato: XX:XX:XX:XX:XX:XX ou XX-XX-XX-XX-XX-XX (pode usar maiúsculas ou minúsculas)', max_length=17, unique=True, validators=[unifi_auth_app.models.validate_mac_address], verbose_name='MAC Address'),
        ),
    ]
