# Generated by Django 5.2.1 on 2025-05-16 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifi_auth_app', '0007_unifiuserstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiuserstatus',
            name='mac_address',
            field=models.CharField(default='00:00:00:00:00:00', max_length=17, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unifiuserstatus',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2025, 5, 16)),
            preserve_default=False,
        ),
    ]
