# Generated by Django 5.2.1 on 2025-05-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifi_auth_app', '0009_alter_unifiuser_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiuser',
            name='vinculo',
            field=models.CharField(choices=[('efetivo', 'Efetivo'), ('comissionado', 'Comissionado')], default='efetivo', max_length=15, verbose_name='Vínculo'),
        ),
    ]
