# Generated by Django 5.2.1 on 2025-05-23 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unifi_auth_app', '0012_alter_unifiuser_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unifiuserstatus',
            name='cadastrado_unifi',
        ),
        migrations.RemoveField(
            model_name='unifiuserstatus',
            name='data_cadastro',
        ),
    ]
