# Generated by Django 4.2.10 on 2025-06-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifi_auth_app', '0013_remove_unifiuserstatus_cadastrado_unifi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('mac_address', models.CharField(max_length=17, verbose_name='Endereço MAC')),
                ('data_acesso', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora do Acesso')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('autorizado', models.BooleanField(default=False, verbose_name='Autorizado')),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
                'ordering': ['-data_acesso'],
            },
        ),
    ]
