# Generated by Django 4.2.10 on 2025-06-09 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unifi_auth_app', '0014_visitante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnifiUserStatus',
        ),
    ]
