# Generated by Django 4.2.10 on 2025-06-12 14:40

from django.db import migrations, models
import django.db.models.deletion
import unifi_auth_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('unifi_auth_app', '0015_delete_unifiuserstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='autorizado',
            field=models.BooleanField(default=False, help_text='Indica se o visitante está autorizado a acessar a rede', verbose_name='Autorizado'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='data_acesso',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o visitante acessou a rede', verbose_name='Data e Hora do Acesso'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='email',
            field=models.EmailField(help_text='E-mail para contato do visitante', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Endereço IP atribuído ao visitante', null=True, verbose_name='Endereço IP'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='mac_address',
            field=models.CharField(blank=True, help_text='Campo mantido para compatibilidade. Use a tabela de dispositivos para novos registros.', max_length=17, null=True, verbose_name='Endereço MAC (Legado)'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='nome',
            field=models.CharField(help_text='Nome completo do visitante', max_length=200, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='telefone',
            field=models.CharField(help_text='Telefone para contato do visitante', max_length=20, verbose_name='Telefone'),
        ),
        migrations.CreateModel(
            name='VisitanteDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitante_mac_address', models.CharField(help_text='Endereço MAC do dispositivo do visitante. Formato: XX:XX:XX:XX:XX:XX', max_length=17, validators=[unifi_auth_app.models.validate_mac_address], verbose_name='Endereço MAC do Dispositivo')),
                ('visitante_nome_dispositivo', models.CharField(blank=True, help_text='Nome amigável para identificar o dispositivo (opcional)', max_length=100, null=True, verbose_name='Nome do Dispositivo')),
                ('visitante_data_cadastro', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o dispositivo foi cadastrado', verbose_name='Data de Cadastro')),
                ('visitante_ultimo_acesso', models.DateTimeField(auto_now=True, help_text='Data e hora do último acesso do dispositivo', verbose_name='Último Acesso')),
                ('visitante_dispositivo_ativo', models.BooleanField(default=True, help_text='Indica se o dispositivo está atualmente autorizado', verbose_name='Dispositivo Ativo')),
                ('visitante', models.ForeignKey(help_text='Visitante ao qual este dispositivo está associado', on_delete=django.db.models.deletion.CASCADE, related_name='visitante_dispositivos', to='unifi_auth_app.visitante', verbose_name='Visitante')),
            ],
            options={
                'verbose_name': 'Dispositivo de Visitante',
                'verbose_name_plural': 'Dispositivos de Visitantes',
                'ordering': ['-visitante_ultimo_acesso'],
                'unique_together': {('visitante', 'visitante_mac_address')},
            },
        ),
    ]
